name: inu
description: A localization tool for Flutter apps based on class generation.
version: 0.0.1
homepage: https://github.com/Arwed-M/inu

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  yaml_mapper: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
